{% set name = "smipoly" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/smipoly-{{ version }}.tar.gz
  sha256: 7f354ca6130104d598f73742937d5c139dc0079a0a0861eeaa6fbb94be0e9267

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - setuptools >=45
    - wheel
    - setuptools-scm >=6.0
    - pip
  run:
    - python >=3.7
    - rdkit >=2020.09.1.0
    - numpy >=1.20.2
    - pandas >=1.2.4

test:
  imports:
    - smipoly
  commands:
    - pip list
  requires:
    - pip

about:
  home: https://github.com/PEJpOhno/SMiPoly
  summary: rule-based virtual polymer library generator
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - PEJpOhno
