{% set name = "smipoly" %}
{% set version = "1.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/smipoly-{{ version }}.tar.gz
  sha256: 572dcaf53452976da312d79939a7dce25099bc81a89c87c0ce2c2a540782a635

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    # - setuptools >=45
    - wheel
    # - setuptools-scm >=6.0
    - pip
    - hatchling >=1.26
  run:
    - python >={{ python_min }}
    - rdkit >=2023.09.1.0
    - numpy >=1.26.0
    - pandas >=2.1.0

test:
  imports:
    - smipoly
  commands:
    - pip list
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/PEJpOhno/SMiPoly
  summary: rule-based virtual polymer library generator
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - PEJpOhno
